---
apiVersion: v1
kind: List
items:
- apiVersion: argoproj.io/v1alpha1
  kind: Application
  metadata:
    name: app-of-apps
    namespace: argocd
  spec:
    project: app-of-apps-project
    source:
      path: app-of-apps/all-apps
      repoURL: https://github.com/lovelinuxalot/argocd-test.git
      targetRevision: HEAD
      directory:
        recurse: true
        jsonnet: {}
    destination:
      namespace: argocd
      server: https://kubernetes.default.svc
    syncPolicy:
      automated:
        selfHeal: true
        prune: true
- apiVersion: argoproj.io/v1alpha1
  kind: AppProject
  metadata:
    name: app-of-apps-project
    namespace: argocd
  spec:
    description: App of Apps Project
    sourceRepos:
    - '*'
    destinations:
    - namespace: argocd
      server: https://kubernetes.default.svc
    clusterResourceWhitelist:
    - group: '*'
      kind: '*'
    orphanedResources:
      warn: false






- apiVersion: argoproj.io/v1alpha1
  kind: Application
  metadata:
    name: argocd-projects
    namespace: argocd
  spec:
    project: argocd
    source:
      path: argocd-projects
      repoURL: ssh://git@bitbucket.anarcon.de:7999/anarcon/gitops.git
      targetRevision: HEAD
      directory:
        recurse: true
        jsonnet: {}
    destination:
      namespace: argocd
      server: https://kubernetes.default.svc
    syncPolicy:
      automated:
        selfHeal: true
        prune: true
---
apiVersion: v1
kind: List
items:
- apiVersion: argoproj.io/v1alpha1
  kind: AppProject
  metadata:
    name: argocd
    namespace: argocd
  spec:
    description: Argocd Project
    sourceRepos:
    - '*'
    destinations:
    - namespace: argocd
      server: https://kubernetes.default.svc
    clusterResourceWhitelist:
    - group: '*'
      kind: '*'
    orphanedResources:
      warn: false
