apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-app-application
  namespace: argocd
spec:
  project: sample-app-project
  source:
    path: test-apps/sample-app
    repoURL: https://github.com/lovelinuxalot/argocd-test.git
    targetRevision: HEAD
    directory:
      recurse: true
      jsonnet: {}
  destination:
    namespace: sample-app-ns
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: sample-app-project
  namespace: argocd
spec:
  description: Project for sample apps
  sourceRepos:
    - '*'
  destinations:
    - namespace: sample-app-ns
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  orphanedResources:
    warn: false