apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitor-app2
  namespace: testing-monitor
  labels:
    app: monitor-app2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: monitor-app2
  template:
    metadata:
      labels:
        app: monitor-app2
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80